platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"
inputs:
  - name: sources
outputs:
  - name: build
caches:
  - path: ~/.gradle/
  - path: ~/.m2/
run:
  path: sh
  args:
  - sources/ci/tasks/build.sh