platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"
inputs:
  - name: sources
    path: ohmypwd
outputs:
  - name: build
caches:
  - path: .gradle/
run:
  path: sh
  args:
  - ohmypwd/ci/tasks/build.sh