---
resources:
  - name: sources
    type: git
    source:
      branch: master
      uri: https://github.com/alek-sys/ohmypwd

  - name: docker
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image}}

jobs:
  - name: build
    plan:
      - get: sources
        trigger: true
      - task: build
        file: sources/ci/tasks/build.yml
      - put: docker
        params:
          build: build
